version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: test.Dockerfile
      target: test
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/uploads
    command: npm run start:dev
    environment:
      - DB_HOST=db
      - DB=devdb
      - DB_USERNAME=devuser
      - DB_PASSWORD=changeme
      - APP_PORT=3000
      - PORT=5432
      - DB_SYNCHRONIZE=true
      - ACCESS_TOKEN_SECRET=secrettoken
      - REFRESH_TOKEN_SECRET=secrettoken1
      - ACCESS_TOKEN_EXPIRATION_TIME=1d
      - REFRESH_TOKEN_EXPIRATION_TIME=1d
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=devdb
      - PORT=5432

volumes:
  dev-db-data:
