name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
        description: "Username for DockerHub authentication"
      DOCKERHUB_TOKEN:
        required: true
        description: "Token for DockerHub authentication"

jobs:
  nestjs:
    name: Nestjs
    runs-on: ubuntu-22.04
    steps:
      - name: Login into DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout DockerHub
        uses: actions/checkout@v4
      - name: Test e2e
        run: docker compose run --rm app sh -c "npm run test:e2e"
      - name: ESLint
        run: docker compose run --rm app sh -c "npm run lint"
